exports.first = [`(flag).flag -> IF(substring((chars).chars) == D"~")`, `(name , address , gender).address -> (((((((D"Address) * (layout_person.street)) * (D",)) * (layout_person.city)) * (D",)) * (layout_person.state)) * (D")) * (layout_person.zip)`, `(name , address , gender).gender -> layout_person.gender`, `(name , address , gender).name -> (((((D"Name) * (layout_person.firstname)) * (D")) * (layout_person.middleinitial)) * (D")) * (layout_person.lastname)`, `16`, `DeclareData exported`, `DeclareData exported`, `GetDetails`, `MyFunc`, `PrintFunc`, `Xform`, `count1`, `count2`, `ds`, `filter1`, `n`, `normalize1`, `normalize2`, `record`, `{
	DATASET : ds
	NO_ITERATIONS : 16
	TRANSFORMATION : Xform
}.flag == 1`, ];
exports.second = [`Xform`, `GetDetails`, `GetDetails`, `GetDetails`, `normalize1`, `count2`, `normalize2`, `normalize2`, `output1`, `output2`, `normalize1`, `MyFunc`, `normalize2`, `normalize1`, `count1`, `filter1`, `n`, `PrintFunc`, `ds`, `filter1`, ];
exports.node = [`(flag).flag -> IF(substring((chars).chars) == D"~")`,`(name , address , gender).address -> (((((((D"Address) * (layout_person.street)) * (D",)) * (layout_person.city)) * (D",)) * (layout_person.state)) * (D")) * (layout_person.zip)`,`(name , address , gender).gender -> layout_person.gender`,`(name , address , gender).name -> (((((D"Name) * (layout_person.firstname)) * (D")) * (layout_person.middleinitial)) * (D")) * (layout_person.lastname)`,`16`,`DeclareData exported`,`GetDetails`,`MyFunc`,`PrintFunc`,`Xform`,`count1`,`count2`,`ds`,`filter1`,`n`,`normalize1`,`normalize2`,`output1`,`output2`,`record`,`{
	DATASET : ds
	NO_ITERATIONS : 16
	TRANSFORMATION : Xform
}.flag == 1`,];
;exports.compound_child=[`(name , address , gender).gender -> layout_person.gender`,`transform3`,`(flag).flag -> IF(substring((chars).chars) == D"~")`,`(name , address , gender).address -> (((((((D"Address) * (layout_person.street)) * (D",)) * (layout_person.city)) * (D",)) * (layout_person.state)) * (D")) * (layout_person.zip)`,`(name , address , gender).name -> (((((D"Name) * (layout_person.firstname)) * (D")) * (layout_person.middleinitial)) * (D")) * (layout_person.lastname)`,`transform1`,];
exports.compound_parent=[`GetDetails`,`Xform`,`Xform`,`GetDetails`,`GetDetails`,`GetDetails`,];
exports.labels=[`output1`,`MyFunc`,`dataset`,`filter1`,`{
	DATASET : ds
	NO_ITERATIONS : 16
	TRANSFORMATION : Xform
}.flag == 1`,`equality`,`filter1`,`n`,`dataset`,`normalize1`,`ds`,`dataset`,`normalize1`,`ds`,`dataset`,`ds`,`record`,`record`,`normalize1`,`16`,`ITERATIONS`,`normalize1`,`Xform`,`transform`,`normalize1`,`Xform`,`transform`,`Xform`,`(flag).flag -> IF(substring((chars).chars) == D"~")`,`assign`,`n`,`normalize1`,`normalize`,`count1`,`filter1`,`filter`,`MyFunc`,`count1`,`dataset`,`output2`,`PrintFunc`,`dataset`,`output2`,`PrintFunc`,`dataset`,`normalize2`,`DeclareData exported`,`dataset`,`normalize2`,`DeclareData exported`,`dataset`,`normalize2`,`count2`,`count`,`count2`,`DeclareData exported`,`dataset`,`normalize2`,`count2`,`ITERATIONS`,`normalize2`,`GetDetails`,`transform`,`normalize2`,`GetDetails`,`transform`,`GetDetails`,`(name , address , gender).name -> (((((D"Name) * (layout_person.firstname)) * (D")) * (layout_person.middleinitial)) * (D")) * (layout_person.lastname)`,`assign`,`GetDetails`,`(name , address , gender).gender -> layout_person.gender`,`assign`,`GetDetails`,`(name , address , gender).address -> (((((((D"Address) * (layout_person.street)) * (D",)) * (layout_person.city)) * (D",)) * (layout_person.state)) * (D")) * (layout_person.zip)`,`assign`,`PrintFunc`,`normalize2`,`normalize`,];