exports.first = [``, ``, `AUTO_INCREMENT`, `CatRecs`, `CatThem`, `Project(DATASET : SomeFile , TRANSFORM : CatThem)`, `SELF.field#catvalues -> (((myrec.field#value1) * (myrec.field#value2)) * (D"-")) * (AUTO_INCREMENT)`, `SELF.field#value1 -> myrec.field#value1`, `SELF.field#value2 -> myrec.field#value2`, `SomeFile`, `myrec`, `record_myrec`, ];
exports.second = [`Project(DATASET : SomeFile , TRANSFORM : CatThem)`, `output1`, `Project(DATASET : SomeFile , TRANSFORM : CatThem)`, `output1`, `Project(DATASET : SomeFile , TRANSFORM : CatThem)`, `CatRecs`, `CatThem`, `CatThem`, `CatThem`, `Project(DATASET : SomeFile , TRANSFORM : CatThem)`, `SomeFile`, `myrec`, ];
exports.node = [`AUTO_INCREMENT`,`CatRecs`,`CatThem`,`Project(DATASET : SomeFile , TRANSFORM : CatThem)`,`SELF.field#catvalues -> (((myrec.field#value1) * (myrec.field#value2)) * (D"-")) * (AUTO_INCREMENT)`,`SELF.field#value1 -> myrec.field#value1`,`SELF.field#value2 -> myrec.field#value2`,`SomeFile`,``,`myrec`,`output1`,`record_myrec`,];
exports.fieldsToNodes_fields = {0 : ["SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2","SELF.field#catvalues","myrec.field#value1","myrec.field#value2","SELF.field#value1","myrec.field#value1","SELF.field#value2","myrec.field#value2",],
1 : ["SELF.field#catvalues","myrec.field#value1","myrec.field#value2","SELF.field#value1","myrec.field#value1","SELF.field#value2","myrec.field#value2",],
2 : ["SELF.field#catvalues","myrec.field#value1","myrec.field#value2",],
3 : ["SELF.field#value1","myrec.field#value1",],
4 : ["SELF.field#value2","myrec.field#value2",],
5 : ["SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2","SELF.field#value1","SELF.field#value2",],
};
exports.fieldsToNodes_nodeName = [`CatRecs`, `CatThem`, `SELF.field#catvalues -> (((myrec.field#value1) * (myrec.field#value2)) * (D"-")) * (AUTO_INCREMENT)`, `SELF.field#value1 -> myrec.field#value1`, `SELF.field#value2 -> myrec.field#value2`, `SomeFile`, ];
exports.compound_child=[`SELF.field#value2 -> myrec.field#value2`,`SELF.field#value1 -> myrec.field#value1`,`SELF.field#catvalues -> (((myrec.field#value1) * (myrec.field#value2)) * (D"-")) * (AUTO_INCREMENT)`,`transform6`,];
exports.compound_parent=[`CatThem`,`CatThem`,`CatThem`,`CatThem`,];
exports.labels=[`output1`,`CatRecs`,`dataset`,`CatRecs`,`Project(DATASET : SomeFile , TRANSFORM : CatThem)`,`hqlproject`,`Project(DATASET : SomeFile , TRANSFORM : CatThem)`,`SomeFile`,`dataset`,`SomeFile`,`myrec`,`dataset`,`myrec`,`record`,`record`,`Project(DATASET : SomeFile , TRANSFORM : CatThem)`,`CatThem`,`transform`,`CatThem`,`SELF.field#catvalues -> (((myrec.field#value1) * (myrec.field#value2)) * (D"-")) * (AUTO_INCREMENT)`,`assign`,`CatThem`,`SELF.field#value1 -> myrec.field#value1`,`assign`,`CatThem`,`SELF.field#value2 -> myrec.field#value2`,`assign`,`CatRecs`,`Project(DATASET : SomeFile , TRANSFORM : CatThem)`,`hqlproject`,];
exports.records = [`record_myrec`, `myrec`, ];
